/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.henryhuang.avrojson;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroDemo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6721108762175954830L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroDemo\",\"namespace\":\"com.github.henryhuang.avrojson\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"version\",\"type\":[\"int\",\"null\"]},{\"name\":\"version_uuid\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Integer version;
  @Deprecated public java.lang.CharSequence version_uuid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroDemo() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param version The new value for version
   * @param version_uuid The new value for version_uuid
   */
  public AvroDemo(java.lang.CharSequence name, java.lang.Integer version, java.lang.CharSequence version_uuid) {
    this.name = name;
    this.version = version;
    this.version_uuid = version_uuid;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return version;
    case 2: return version_uuid;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: version = (java.lang.Integer)value$; break;
    case 2: version_uuid = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.Integer getVersion() {
    return version;
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Integer value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'version_uuid' field.
   * @return The value of the 'version_uuid' field.
   */
  public java.lang.CharSequence getVersionUuid() {
    return version_uuid;
  }

  /**
   * Sets the value of the 'version_uuid' field.
   * @param value the value to set.
   */
  public void setVersionUuid(java.lang.CharSequence value) {
    this.version_uuid = value;
  }

  /**
   * Creates a new AvroDemo RecordBuilder.
   * @return A new AvroDemo RecordBuilder
   */
  public static com.github.henryhuang.avrojson.AvroDemo.Builder newBuilder() {
    return new com.github.henryhuang.avrojson.AvroDemo.Builder();
  }

  /**
   * Creates a new AvroDemo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroDemo RecordBuilder
   */
  public static com.github.henryhuang.avrojson.AvroDemo.Builder newBuilder(com.github.henryhuang.avrojson.AvroDemo.Builder other) {
    return new com.github.henryhuang.avrojson.AvroDemo.Builder(other);
  }

  /**
   * Creates a new AvroDemo RecordBuilder by copying an existing AvroDemo instance.
   * @param other The existing instance to copy.
   * @return A new AvroDemo RecordBuilder
   */
  public static com.github.henryhuang.avrojson.AvroDemo.Builder newBuilder(com.github.henryhuang.avrojson.AvroDemo other) {
    return new com.github.henryhuang.avrojson.AvroDemo.Builder(other);
  }

  /**
   * RecordBuilder for AvroDemo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroDemo>
    implements org.apache.avro.data.RecordBuilder<AvroDemo> {

    private java.lang.CharSequence name;
    private java.lang.Integer version;
    private java.lang.CharSequence version_uuid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.henryhuang.avrojson.AvroDemo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.version)) {
        this.version = data().deepCopy(fields()[1].schema(), other.version);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.version_uuid)) {
        this.version_uuid = data().deepCopy(fields()[2].schema(), other.version_uuid);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroDemo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.henryhuang.avrojson.AvroDemo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.version)) {
        this.version = data().deepCopy(fields()[1].schema(), other.version);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.version_uuid)) {
        this.version_uuid = data().deepCopy(fields()[2].schema(), other.version_uuid);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.Integer getVersion() {
      return version;
    }

    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder setVersion(java.lang.Integer value) {
      validate(fields()[1], value);
      this.version = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder clearVersion() {
      version = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'version_uuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getVersionUuid() {
      return version_uuid;
    }

    /**
      * Sets the value of the 'version_uuid' field.
      * @param value The value of 'version_uuid'.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder setVersionUuid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.version_uuid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'version_uuid' field has been set.
      * @return True if the 'version_uuid' field has been set, false otherwise.
      */
    public boolean hasVersionUuid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'version_uuid' field.
      * @return This builder.
      */
    public com.github.henryhuang.avrojson.AvroDemo.Builder clearVersionUuid() {
      version_uuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public AvroDemo build() {
      try {
        AvroDemo record = new AvroDemo();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.version = fieldSetFlags()[1] ? this.version : (java.lang.Integer) defaultValue(fields()[1]);
        record.version_uuid = fieldSetFlags()[2] ? this.version_uuid : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
